### ISSUE TITLE
High CPU load while active

### ISSUE THREAD

**Issue by fragtion** [staaldraad/tcpprox#8]
Firstly thanks for this marvellous piece of software, it is very useful

Unfortunately I am noticing very high CPU load while the process is running. I presume this is because of the continuous loop while waiting for data stream from both sockets?  Is there no known way to alleviate this? It seems a bit strange that a "simple" TCP proxy  process should consume such high system load ..

Regards

**Comment by staaldraad** [comment]
Hi! Thank you 😄 

I definitely need to revisit this and apply some optimisation. Most of this was written while still learning Go, I'm sure there are some rookie mistakes that can be rectified.

**Comment by staaldraad** [comment]
@fragtion if you want to give the new version a try 👍 

I've spent some time moving everything to pipes which should be more efficient: https://github.com/staaldraad/tcpprox/pull/10
However in my tests this is on par with the previous version in terms of performance. I'm not running into CPU usage issues with either version.

**Comment by fragtion** [comment]
Good news! Thanks, I will try it & advise if I run into anything noteworthy ;)

**Comment by staaldraad** [comment]
I did an arbitrary test across a few different systems and I'm not seeing excessive load. 

Test: tcpprox --> ssh through tcpprox --> nyncat

With the `-raw` option (basically only act as proxy and don't print anything to screen) I was hovering at 0.7% CPU usage:

![nein](https://user-images.githubusercontent.com/4200832/90399895-fbf65900-e09b-11ea-8a60-d01332a83b95.png)

Default operation, proxying, hexDump formatting and dumping to screen, this goes up to 3.3% CPU usage:

![nein2](https://user-images.githubusercontent.com/4200832/90400064-2f38e800-e09c-11ea-9eb3-ff8378bae60f.png)
